import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Login from './components/Login'
import Footer from './components/Layout/Footer'
import Script from 'next/script'
import { PrismaClient } from '@prisma/client'

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Learning Platform</title>
        <meta name="mcs" content="Generated by create next app" />
        <link rel="icon" href="/images/getsitelogo.png" />
        <link rel="stylesheet" href="https://unpkg.com/flowbite@1.5.3/dist/flowbite.min.css" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <p href="https://nextjs.org" className=''>LMS</p>
        </h1>

        <div className={styles.grid}>
          <Login data = {props.user}/>
        </div>
      </main>

      <Footer />
      <Script src="https://unpkg.com/@themesberg/flowbite@latest/dist/flowbite.bundle.js"></Script>
    </div>
  )
}

const prisma = new PrismaClient();

export const getServerSideProps = async (context) => {

  const user = await prisma.user.findMany();

  return {
      props: {
          user: JSON.parse(JSON.stringify(user))
      }
  }
}
